services:

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_parkingmeter
      MONGO_INITDB_ROOT_PASSWORD: pass_parkingmeter
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rede-parkingmeter

#java17:
#  image: openjdk:17-jdk-alpine
#  ports:
#    - "8080:8080"
#  volumes:
#    - ./target:/app/target
#  working_dir: /app
#  command: sh -c 'java -jar target/*.jar'
#  depends_on:
#    - mongodb
#  environment:
#    SPRING_DATA_MONGODB_HOST: mongo-container
#    SPRING_DATA_MONGODB_PORT: 27017
#    SPRING_DATA_MONGODB_DATABASE: parkingmeterdb
#    SPRING_DATA_MONGODB_USERNAME: user_parkingmeter
#    SPRING_DATA_MONGODB_PASSWORD: pass_parkingmeter
#  networks:
#    - rede-parkingmeter

networks:
  rede-parkingmeter:
    driver: bridge