services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_parkingmeter
      MONGO_INITDB_ROOT_PASSWORD: pass_parkingmeter
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - rede-parkingmeter

networks:
  rede-parkingmeter:
    driver: bridge